### ISSUE TITLE
k8s拉取tis:4.0.1镜像失败

### ISSUE THREAD

**Issue by zzxVv** [datavane/tis#373]
k8s部署tis-4.0.1时，出现镜像拉取报错，将配置中版本修改为4.0.0可正常拉取，以下时配置中拉取镜像url，和git中的tis-console配置文件一致。     
```
 volumeMounts:
            - name: tis-config-volume
              mountPath: /opt/app/tis-uber/web-start/conf/tis-web-config/
            - name: tis-console-pvc
              mountPath: "/opt/data"
          image: registry.cn-hangzhou.aliyuncs.com/tis/tis-console:4.0.1
```
